# Generated by Django 3.1.1 on 2020-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robowizardemployee',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
    ]
