# Generated by Django 3.1.1 on 2020-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200930_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robowizardemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-Mail'),
        ),
    ]
