# Generated by Django 3.1.2 on 2020-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200930_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robowizardemployee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
