# Generated by Django 3.1.2 on 2020-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20201003_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='robowizardemployee',
            name='permission_accounting',
            field=models.BooleanField(default=False, verbose_name='Бухгалтерия'),
        ),
        migrations.AddField(
            model_name='robowizardemployee',
            name='permission_administration',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='robowizardemployee',
            name='permission_sales',
            field=models.BooleanField(default=False, verbose_name='Отдел продаж'),
        ),
        migrations.AddField(
            model_name='robowizardemployee',
            name='permission_service',
            field=models.BooleanField(default=False, verbose_name='Сервисный отдел'),
        ),
    ]
