# Generated by Django 3.1.2 on 2020-11-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201110_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robowizardemployee',
            options={},
        ),
    ]
