# Generated by Django 3.1.2 on 2020-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('changelog', '0002_auto_20201110_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.TextField(verbose_name='Изменяемые данные модели'),
        ),
    ]
