# Generated by Django 3.1.1 on 2020-10-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Контроллер')),
            ],
        ),
        migrations.CreateModel(
            name='Integrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Интегратор')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, unique=True, verbose_name='Город')),
            ],
        ),
        migrations.AlterField(
            model_name='arm',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('serial_number', models.CharField(max_length=32, verbose_name='Серийный номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.client',
                                                verbose_name='Клиент')),
                ('controller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.controller',
                                                    verbose_name='Контроллер')),
                ('integrator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    to='robots.integrator', verbose_name='Интегратор')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.arm',
                                               verbose_name='Модель')),
            ],
        ),
        migrations.AddField(
            model_name='integrator',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='robots.location', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='client',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='robots.location', verbose_name='Местоположение'),
        ),
    ]
