# Generated by Django 3.1.1 on 2020-10-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0002_auto_20201002_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Файл')),
                ('file_path', models.CharField(max_length=1024, verbose_name='Путь к файлу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Отчёт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('robot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot',
                                               verbose_name='Робот')),
            ],
        ),
    ]
