# Generated by Django 3.1.1 on 2020-10-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0003_backup_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='backup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='robots.backup', verbose_name='Бэкап'),
        ),
    ]
