# Generated by Django 3.1.1 on 2020-10-02 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0004_robot_backup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='backup_id',
        ),
        migrations.AddField(
            model_name='backup',
            name='robot_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='robots.robot'),
            preserve_default=False,
        ),
    ]
