# Generated by Django 3.1.1 on 2020-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0005_auto_20201002_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='robot_id',
            new_name='service_id',
        ),
        migrations.AddField(
            model_name='robot',
            name='main_backup',
            field=models.CharField(default=None, max_length=512, verbose_name='Путь к бэкапу'),
            preserve_default=False,
        ),
    ]
