# Generated by Django 3.1.1 on 2020-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0006_auto_20201002_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='main_backup',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к бэкапу'),
        ),
    ]
