# Generated by Django 3.1.2 on 2020-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0010_auto_20201003_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={},
        ),
        migrations.AddField(
            model_name='robot',
            name='main_backup_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Бэкап'),
        ),
    ]
