# Generated by Django 3.1.2 on 2020-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0011_auto_20201003_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='main_backup_file',
            field=models.FileField(blank=True, null=True, upload_to='backups/', verbose_name='Бэкап'),
        ),
    ]
