# Generated by Django 3.1.2 on 2020-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0012_auto_20201006_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='main_backup',
        ),
        migrations.RemoveField(
            model_name='service',
            name='report_path',
        ),
        migrations.AddField(
            model_name='robot',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(default='demo', upload_to='backups/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
