# Generated by Django 3.1.2 on 2020-10-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0014_auto_20201007_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='integrator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.integrator', verbose_name='Интегратор'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.arm', verbose_name='Модель'),
        ),
    ]
