# Generated by Django 3.1.2 on 2020-11-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_auto_20201007_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
