# Generated by Django 3.1.2 on 2020-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0016_auto_20201110_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='file_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Файл'),
        ),
    ]
