# Generated by Django 3.1.2 on 2020-11-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0017_robot_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='file_data',
        ),
    ]
