# Generated by Django 3.1.2 on 2020-11-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_workingday_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingPlaces',
            new_name='WorkingPlace',
        ),
    ]
