# Generated by Django 3.1.2 on 2020-11-13 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_auto_20201113_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.robowizardemployee', verbose_name='Работник'),
        ),
    ]
