# Generated by Django 3.1.2 on 2020-11-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20201113_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingdaypart',
            old_name='location',
            new_name='location_id',
        ),
    ]
